BladeDISC patch 20221101
1, Build related changes:
* No force -std=c++17 for cuda.
  https://github.com/pai-disc/tensorflow/commit/af4d5a07589c1d30c14c76aba6592554210451a5

* workaround compilation error on GCC 7.3.1: (#19)
  like: undefined reference to `std::function<tensorflow::StatusOr<xla::Shape> (xla::Shape const&, bool, mlir::XlaLayoutPreference)>::function()'

* [to #35355928] fix build issue when enabling MLIR_GPU_TO_CUBIN_PASS_ENABLE

* disable `-Werror=unused-result`
* disable `noincompatible_remove_legacy_whole_archive`
* add miss dependency `//tensorflow/compiler/xla/stream_executor:dnn_proto_cc_impl`

2, hlo related changes:

* [to #35377611] feat: bufferize DotOp and DotGeneralOp.
  remove community DotGeneralOp bufferizer as well
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/5885662

* [to #35377611] feat: bufferize ConvOp and DynamicConvOp.
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/5910553

* [to #37276187] feat: bufferize mhlo.log1pOp
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6675686

* [to #36574644] [MLIR] [DISC] Add reverse op in lmhlo
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6364791

* support RoundNearestEvenOp (#20)
* support RoundOp (#21)
* add const folding support for mhlo.TransposeOp
* disable some static checks of mhlo.dot_general
  `tf.BatchMatmul(tensor<?x?x?xf32>, tensor<4x?x?xf32>)` is valid, while the `tf.BatchMatmul` tf2mhlo converter does not handle shape propagation between the lhs & rhs, leading to some of the static check of `dot_general` failed. Just disable the check as a workaround.

* [to #35355928] fix missing Elementwise traits of some special ops
* [to #35355928] fix a bug in lmhlo structured interface
* enhance `maybeCastTo` to support casting between i64 and i32.
* cast to i64 only if index type in DynamicIotaBroadcast pattern.
* add a patch not to fold UnrealizedConversionCastOp with ui/si type

3, TF related changes:

* lower tf.GatherV2 op to mhlo in dynamic shape
* lower tf.DepthwiseConv2DNative op to mhlo in dynamic shape
* lower tf.StridedSlice op to mhlo in dynamic shape
* lower tf.DynamicStitchOp to mhlo in dynamic shape
* lower tf.BatchMatMulOp op to mhlo in dynamic shape
* lower tf.Conv2DBackpropInputOp/tf.Conv2DBackpropFilterOp  to mhlo in dynamic shape

* support tf.Range wit negative stride
* support tf.StridedSlice with new_axis_mask
* add mhlo_disc dependency in xla legalize_tf
* legalize quantized tf const before lowering to mhlo

* add tf2mhlo support for tf.BatchMatMul
* bugfix: only handling non-const begin/end in ConvertStridedSliceOpDynamic
* bugfix: using tf.TileOp static tf2mhlo conversion only when all ins/outs have static shape
* bugfix: size of begin/end/strides < the rank of input
* bugfix: disable TF_RandomUniformOp in tf->mhlo
* fix a bug in tf.SigmoidGradOp legalize pattern
* fix a bug in ConvertSplitOp pattern
* fix a bug in ConvertUnpackOp pattern

* [to #36775150] feat: to support multi StreamExecutor by stream as cache key
  In the original design of StreamExecutor, one StreamExecutor maps to
  each device ordinal and owns one cudnnHandle. This means in multiple
  stream applications, there will be only one StreamExecutor for each GPU
  device. We observed dramatic performance degrade due to the lock in the
  SE, refer to https://yuque.antfin-inc.com/pai/blade/irdw7g. This commit
  revises the executor cache, so that there will be multiple
  StreamExecutors for each gpu stream.
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6455216

* [to #36574492]feat: dynamic strided slice op supports negative strides
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6425899

3, ROCM/DCU related changes:

* [to #37531008] feat: Support building for DCU
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6897356

* [to #37531008] allow asigned stream in se for rocm backend
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6918944

* [to #37383705] patch: Add shfl.sync.bfly lowering to ROCm
  Link: https://code.aone.alibaba-inc.com/algo/tensorflow_google/codereview/6937184

* [to #39814120] Fix config for Macro and support gfx90a

* [rocm] remove -fno-canonical-system-headers as hipcc does not support

* [to #37531008] expose some more methods in gpu_backend_lib.h

4, others:

* update gitignore
* Add llvm patch to fix error GVN on shared memory load. (#4)